# YueMi Libs Configuration

# Do not change this version!
config-version: 3

# Configure third-party hooks and integration
hooks:
  economy:
    enabled: true
    # The economy provider to hook (e.g. "Vault")
    provider: "Vault"
  items:
    # Whether to hook into CraftEngine to support its custom items
    craftengine:
      enabled: true

# Configuration for item providers
providers:
  minecraft:
    # How strictly to match items when checking or taking them from player inventories.
    # Options:
    # - ID: Matches only by Material ID type (e.g. minecraft:stone)
    # - CUSTOM_MODEL_DATA: Matches by Material ID type and Custom Model Data
    # - NBT: Matches strictly (all metadata / NBT must match)
    match-mode: "ID"
